name: PowerSigns
author: redslime
version: 1.13.1
main: redsli.me.powersigns.PowerSignsPlugin
website: https://github.com/redslime/PowerSigns
depend: [Vault]
api-version: 1.13

commands:
  powersigns:
    aliases: [ps, powersign]

permissions:
  powersigns.sign.use:
    default: true
  powersigns.sign.create.self:
    default: true
  powersigns.limit.default:
    default: true