name: PowerSigns
author: redslime
version: 1.0.1
main: redsli.me.powersigns.PowerSignsPlugin
website:
depend: [Vault]

commands:
  powersigns:
    aliases: [ps, powersign]

permissions:
  powersigns.sign.use:
    default: true
  powersigns.sign.create.self:
    default: true